import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createApp } from '../server.mjs';
const password='test-only-passphrase-123';
async function harness(t){
  const dir=await mkdtemp(join(tmpdir(),'acs-api-')),filename=join(dir,'acs.sqlite');
  let server,base;
  const start=async()=>{server=createApp({filename});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));base=`http://127.0.0.1:${server.address().port}`;};
  const stop=()=>new Promise(resolve=>server.close(resolve));
  await start();t.after(async()=>{await stop();await rm(dir,{recursive:true,force:true});});
  const request=async(path,method='GET',data,cookie='',extra={})=>{const response=await fetch(base+path,{method,headers:{Origin:base,'Content-Type':'application/json',Cookie:cookie,...extra},body:data===undefined?undefined:JSON.stringify(data)});return {status:response.status,body:await response.json(),cookie:response.headers.get('set-cookie')?.split(';')[0],headers:response.headers};};
  return {request,restart:async()=>{await stop();await start();}};
}
test('accounts enforce access, preserve shared data, prevent stale saves, and revoke sessions',async t=>{
  const {request:r,restart}=await harness(t);
  assert.equal((await r('/api/workspace')).status,401);
  assert.equal((await r('/api/setup','POST',{email:'coach@example.test',password},{},{Origin:'https://other.test'})).status,403);
  const coach=await r('/api/setup','POST',{email:'coach@example.test',password});assert.equal(coach.status,200);
  assert.match(coach.headers.get('set-cookie'),/HttpOnly; SameSite=Strict/);
  const cookie=coach.cookie;
  assert.equal((await r('/api/setup','POST',{email:'other@example.test',password})).status,403);
  assert.equal((await r('/api/login','POST',{email:'coach@example.test',password:'incorrect-password'})).status,401);
  const state={schemaVersion:1,athletes:[{id:'A1',name:'One',level:1},{id:'A2',name:'Two',level:2}],records:[{id:'R1',athleteId:'A2',metric:'cmj',value:25}],plans:[{id:'P1',athleteId:'A1',block:'A',title:'Strength',status:'planned',isDeload:true,exercises:[{name:'Squat',sets:3,reps:4,load:30}]},{id:'P2',athleteId:'A2',block:'C',status:'planned',exercises:[]}],workouts:[]};
  assert.equal((await r('/api/workspace','PUT',{revision:0,data:state},cookie)).status,200);
  assert.equal((await r('/api/workspace','PUT',{revision:0,data:state},cookie)).status,409);
  assert.equal((await r('/api/accounts','POST',{email:'athlete@example.test',password,role:'athlete',athleteId:'missing'},cookie)).status,400);
  assert.equal((await r('/api/accounts','POST',{email:'athlete@example.test',password,role:'athlete',athleteId:'A1'},cookie)).status,201);
  const athlete=(await r('/api/login','POST',{email:'athlete@example.test',password})).cookie;
  const visible=await r('/api/workspace','GET',undefined,athlete);
  assert.deepEqual(visible.body.data.athletes.map(a=>a.id),['A1']);assert.equal(visible.body.data.records.length,0);assert.deepEqual(visible.body.data.plans.map(p=>p.id),['P1']);
  assert.equal((await r('/api/workspace','PUT',{revision:1,data:state},athlete)).status,403);
  assert.equal((await r('/api/accounts','POST',{email:'evil@example.test',password,role:'coach'},athlete)).status,403);
  assert.equal((await r('/api/accounts','GET',undefined,athlete)).status,403);
  assert.equal((await r('/api/accounts','DELETE',{id:'anything'},athlete)).status,403);
  assert.equal((await r('/api/accounts','DELETE',{id:coach.body.user.id},cookie)).status,400);
  assert.equal((await r('/api/workouts','POST',{planId:'P2',done:[],note:''},athlete)).status,403);
  assert.equal((await r('/api/workouts','POST',{planId:'P1',done:['yes'],note:''},athlete)).status,400);
  const logged=await r('/api/workouts','POST',{planId:'P1',done:[true],note:'Completed'},athlete);
  assert.equal(logged.status,201);assert.equal(logged.body.data.workouts[0].progressionEligible,false);assert.equal(logged.body.data.workouts[0].athleteId,'A1');
  assert.equal((await r('/api/workouts','POST',{planId:'P1',done:[true],note:''},athlete)).status,409);
  const invalid=structuredClone(state);invalid.records[0].athleteId='missing';
  assert.equal((await r('/api/workspace','PUT',{revision:2,data:invalid},cookie)).status,400);
  const noProfile=structuredClone(state);noProfile.athletes.shift();noProfile.plans.shift();
  assert.equal((await r('/api/workspace','PUT',{revision:2,data:noProfile},cookie)).status,400);
  const second=(await r('/api/login','POST',{email:'athlete@example.test',password})).cookie;
  assert.equal((await r('/api/password','POST',{currentPassword:'wrong',password:'replacement-password'},athlete)).status,403);
  assert.equal((await r('/api/password','POST',{currentPassword:password,password:'replacement-password'},athlete)).status,200);
  assert.equal((await r('/api/workspace','GET',undefined,second)).status,401);
  assert.equal((await r('/api/login','POST',{email:'athlete@example.test',password})).status,401);
  await restart();
  const persisted=await r('/api/workspace','GET',undefined,cookie);
  assert.equal(persisted.status,200);assert.equal(persisted.body.data.workouts.length,1);assert.equal(persisted.body.revision,2);
  const accounts=(await r('/api/accounts','GET',undefined,cookie)).body.accounts;
  const athleteId=accounts.find(a=>a.role==='athlete').id;
  assert.equal((await r('/api/accounts','DELETE',{id:athleteId},cookie)).status,200);
  assert.equal((await r('/api/workspace','GET',undefined,athlete)).status,401);
  assert.equal((await r('/api/workspace','GET',undefined,cookie)).body.data.workouts.length,1);
  assert.equal((await r('/api/logout','POST',{},cookie)).status,200);assert.equal((await r('/api/workspace','GET',undefined,cookie)).status,401);
});
test('server does not expose private files or allow production bootstrap',async t=>{
  const {request:r}=await harness(t);
  for(const path of ['/data/acs.sqlite','/server.mjs','/package.json','/AGENTS.md','/server/store.mjs','/src/domain.test.js'])assert.equal((await r(path)).status,404,path);
  assert.throws(()=>createApp({filename:':memory:',production:true}),/HTTPS APP_ORIGIN/);
});
test('login attempts are limited',async t=>{
  const {request:r}=await harness(t);
  for(let i=0;i<20;i++)assert.equal((await r('/api/login','POST',{email:'nobody@example.test',password})).status,401);
  assert.equal((await r('/api/login','POST',{email:'nobody@example.test',password})).status,429);
});

test('sex is validated and persisted; authenticated leaderboards expose only ranking summaries',async t=>{
  const {request:r,restart}=await harness(t);
  assert.equal((await r('/api/leaderboards')).status,401);
  const coach=await r('/api/setup','POST',{email:'coach@example.test',password}),cookie=coach.cookie;
  const data={schemaVersion:1,athletes:[{id:'F1',name:'Girl',level:1,sex:'female'},{id:'M1',name:'Boy',level:1,sex:'male',baselines:[{name:'Private lift',startWeight:30}]},{id:'U1',name:'Not recorded',level:1}],records:[{id:'RF',athleteId:'F1',metric:'bench',value:90,date:'2026-01-01',note:'Private note'},{id:'RM',athleteId:'M1',metric:'bench',value:100,date:'2026-01-02',note:'Private note'},{id:'RU',athleteId:'U1',metric:'bench',value:200}],plans:[],workouts:[]};
  const invalid=structuredClone(data);invalid.athletes[0].sex='invalid';
  assert.equal((await r('/api/workspace','PUT',{revision:0,data:invalid},cookie)).status,400);
  assert.equal((await r('/api/workspace','PUT',{revision:0,data},cookie)).status,200);
  await r('/api/accounts','POST',{email:'athlete@example.test',password,role:'athlete',athleteId:'F1'},cookie);
  const athlete=(await r('/api/login','POST',{email:'athlete@example.test',password})).cookie;
  assert.equal((await r('/api/workspace','PUT',{revision:1,data},athlete)).status,403);
  const rankings=await r('/api/leaderboards','GET',undefined,athlete);
  assert.equal(rankings.status,200);
  const bench=rankings.body.leaderboards.find(b=>b.metricId==='bench');
  assert.deepEqual(bench.girls.map(e=>e.name),['Girl']);assert.deepEqual(bench.boys.map(e=>e.name),['Boy']);
  assert.deepEqual(Object.keys(bench.boys[0]).sort(),['athleteId','date','name','rank','value']);
  assert.ok(!JSON.stringify(rankings.body).includes('Private'));
  const own=(await r('/api/workspace','GET',undefined,athlete)).body.data;
  assert.deepEqual(own.athletes.map(a=>a.id),['F1']);assert.deepEqual(own.records.map(a=>a.id),['RF']);
  await restart();assert.equal((await r('/api/workspace','GET',undefined,cookie)).body.data.athletes[0].sex,'female');
  data.athletes[2].sex='female';
  assert.equal((await r('/api/workspace','PUT',{revision:1,data},cookie)).status,200);
  const updated=(await r('/api/leaderboards','GET',undefined,athlete)).body.leaderboards.find(b=>b.metricId==='bench');
  assert.deepEqual(updated.girls.map(e=>e.name),['Not recorded','Girl']);
  data.athletes[2].sex=null;
  assert.equal((await r('/api/workspace','PUT',{revision:2,data},cookie)).status,200);
  assert.equal((await r('/api/leaderboards','GET',undefined,cookie)).body.leaderboards.find(b=>b.metricId==='bench').girls.length,1);
});
